name: build

on:
  push:
    branches:
      - main
      - master
      - experimental-apex-parser
    tags:
      - '**'
  pull_request:
  merge_group:
  schedule:
    # build it monthly: At 04:00 on day-of-month 1.
    - cron:  '0 4 1 * *'
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      # read to fetch code (actions/checkout)
      # write to push code to gh-pages, create releases
      # note: forked repositories will have maximum read access
      contents: write
    continue-on-error: false
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

