name: Regenerate CHANGELOG and dist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  regenerate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Compare the expected and actual CHANGELOG.md
        run: |
          if [ "$(git diff CHANGELOG.md | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            echo "changelog=outdated" >> $GITHUB_ENV
          else
            echo "changelog=current" >> $GITHUB_ENV
          fi

      - name: Push changes to CHANGELOG.md
        if: ${{ github.repository == 'pmd/pmd-github-action' && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && env.changelog == 'outdated' }}
        run: |
          git config --local user.email "pmd-bot@users.noreply.github.com"
          git config --local user.name "GitHub Actions (pmd-bot)"
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && git push origin main

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20

      - name: Push changes to dist/
        if: ${{ github.repository == 'pmd/pmd-github-action' && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && env.dist == 'outdated' }}
        run: |
          git config --local user.email "pmd-bot@users.noreply.github.com"
          git config --local user.name "GitHub Actions (pmd-bot)"
          git add dist && git commit -m 'Updated dist' && git push origin main
