name:  SPOTLESS Static Code Analysis

on: [push]
jobs:
  spotless:
    runs-on: ubuntu-latest
  
    steps:         
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
      - name: gradle caching
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: spotlessCheck
        run: ./gradlew spotlessCheck

