name:  SPOTLESS Static Code Analysis

on: [push]
jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/checkout@v4

    - name: assemble testClasses
      run: ./gradlew assemble testClasses
        
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
        with:
          settings-path: 'rules/eclipse-java-google-style.xml'
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew spotlessCheck

      
