name: StyleCode

on:
  pull_request:
  push:
    branches:
      - main
      - feature/**
      - 'releases/**'
  workflow_dispatch:

jobs:
  pmd-analyser-check:
    name: PMD Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          version: '6.40.0'
          sourcePath: 'src'
          rulesets: 'rules/maven-pmd-plugin-custom-rules.xml'
      - uses: ./
        with: 
         path: '**/pmd.xml'
