name: StyleCode

on: push

jobs:
   style-code:
    name: Check code base
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

       -name: Run StyleCode
        uses: github/super-linter@v3
        env: main
        DEFAUKT_BRANCH: main
