name: Publish

# Manual or automatic release
on:
  release:
    types: [published, edited]

jobs:
  pmd-analyser-check:
    name: PMD Static Code Analysis
    permissions:
      security-events: write
      actions: read
      contents: read
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          
      - name: Run Checkout Repository
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20

        env:
          GITHUB_TOKEN: ${{ github.token }}
