name: StyleCode

on:
  pull_request:
  push:
    branches:
      - main
      - feature/**
      - 'releases/**'
  workflow_dispatch:

jobs:
  pmd-analyser-check:
    name: PMD Static Code Analysis
    permissions:
      security-events: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

     - name: Setup Environment
      shell: bash
      run: |
        echo "LANG=en_US.UTF-8" >> $GITHUB_ENV
        echo "PMD_CI_SCRIPTS_URL=https://raw.githubusercontent.com/pmd/build-tools/master/scripts" >> $GITHUB_ENV
